### ISSUE TITLE
why wh en wiki-lit ?

### ISSUE THREAD

**Issue by lxjv** [LITdevs/docs#1]
:skull:

( or is this just vukky testing shit, in which case carry on )

**Comment by vtheskeleton** [comment]
We decided to make the documentation for Painfull on docs.litdevs.org instead to make it more documentation like

**Comment by lxjv** [comment]
fair enough

**Comment by Vukkyy** [comment]
i keep reading the title as "why wh english wiki-lit?"

**Comment by vtheskeleton** [comment]
> i keep reading the title as "why wh english wiki-lit?"

i spent a solid minute trying to figure out what you mean, i was just like "but that is what it says"

**Comment by lxjv** [comment]
no i was just **Extremely** tired when i made that issue
